### ISSUE TITLE
게시글 작성 페이지

### ISSUE THREAD

**Issue by possiblly** [realKamja/GuguCon_front#7]
## 필요한 기능
- 게시글 작성 페이지를 구현합니다.

## 해야 할 일 
- [x] 사이트 구성
- [x] API 연결
- [x] #11 
- [ ] 검증

## 추가 컨텍스트
- @possiblly -> @jjh4450로 담당자 변경됨

**Comment by jjh4450** [comment]
#11 버그를 발견해 수정 조치했습니다. 같이 테스트 진행하면 될 거 같습니다.
